add oidc_config support in schema.go
kyma-incubator/terraform-provider-gardener pull request #39
Opened 2020-01-16 02:36 UTC by neo-liang-sap

during my utilization of terraform-provider-gardener i found in the spec->kubernetes->kube_api_server, the oidc_config part is implemented in https://github.com/kyma-incubator/terraform-provider-gardener/blob/6221849d07f099d83c1f76281a5ea07df7f55ff6/expand/expand_spec.go#L322 , but not exposed in schema_shoot.go https://github.com/kyma-incubator/terraform-provider-gardener/blob/301c93bd06e57bb52483daad1b26411b7fc95fcb/shoot/schema_shoot.go#L104

so i prepared this PR to add implementation for oidc_config

Tested locally with sth like this
in examples/aws/main.tf , and then run `tf init`, `tf plan`
```
    kubernetes {
      version = "1.15.4"
      kube_api_server {
        enable_basic_authentication = false
        oidc_config {
          client_id = "aaa"
          groups_claim = "aaa"
          issuer_url = "aaa"
          username_claim = "aaa"
      }
     }
    }
```

2020-01-16 12:58 UTC, clebs approved these changes

2020-01-16 13:25 UTC, clebs requested changes
Hi @neo-liang-sap,
thanks again for your contribution!

I just tested this change and all seems fine except for one thing, when trying to execute `terraform destroy` after the cluster is created, I get the following error:
`Error: shoots.garden.sapcloud.io "test-cluster" is forbidden: must have a "confirmation.garden.sapcloud.io/deletion" annotation to delete`

Could it be that you need to pull the latest changes on master into your branch? It looks like your PR is still using the old API version.

2020-01-16 13:46 UTC, neo-liang-sap commented
Hi @clebs :

Thanks for reviewing this, i double-checked my branch, it contains latest commits.

I review the commit i submitted several days ago - for update from `garden.sapcloud.io` to `core.gardener.cloud`
https://github.com/kyma-incubator/terraform-provider-gardener/commit/677de9546fe37fd2490f302f76599e976bd2701c

These two lines update annotation from `confirmation.garden.sapcloud.io/deletion` to `confirmation.core.gardener.cloud`

https://github.com/kyma-incubator/terraform-provider-gardener/commit/677de9546fe37fd2490f302f76599e976bd2701c#diff-77ba03a898e7196a3344e1ec87403d7bR25

https://github.com/kyma-incubator/terraform-provider-gardener/commit/677de9546fe37fd2490f302f76599e976bd2701c#diff-6d56a7bf238a7c57fbbbd8c13ec60607R94

So while trying to destroy the shoot cluster, `confirmation.core.gardener.cloud` (new api) is annonated to true but seems server still request old meta data `confirmation.garden.sapcloud.io/deletion`?

What's your suggestion? should i revert above two line to `confirmation.garden.sapcloud.io/deletion`?

Thanks.
-Neo

2020-01-16 13:56 UTC, neo-liang-sap commented
thanks for @ialidzhikov pointing out - see comments in https://github.com/kyma-incubator/terraform-provider-gardener/pull/38

i've updated this PR to fix this

2020-01-16 14:17 UTC, clebs commented
HI @neo-liang-sap, please see my answer on #38. We need to properly do the migration to the new API.

Please reapply this PR after #38 is reverted.
Thanks!

2020-01-16 15:00 UTC, neo-liang-sap commented
this PR is updated as https://github.com/kyma-incubator/terraform-provider-gardener/pull/42 is merged to master and hence this PR rebase master to get latest code base

2020-01-16 15:01 UTC, neo-liang-sap commented
this PR is updated as https://github.com/kyma-incubator/terraform-provider-gardener/pull/42 is merged to master and hence this PR rebase master to get latest code base

2020-01-17 15:50 UTC, clebs approved these changes

2020-01-18 07:13 UTC, merged