Update readme
kyma-incubator/terraform-provider-gardener pull request #8
Opened 2019-09-18 12:39 UTC by obadrawi

Create README files

2019-09-20 14:24 UTC, bszwarc requested changes
Initial comments :)

2019-09-20 14:24 UTC, bszwarc commented on README.md
> +==================
```suggestion

```
We don't need this one :)

2019-09-20 14:24 UTC, bszwarc commented on README.md
General comment:
I would adjust this README file to follow these guidelines: https://github.com/kyma-project/community/blob/master/guidelines/repository-guidelines/repository-template/README.md 
and have a specific structure.

My suggested structure would be:

## Overview
What is the terraform provider for Gardener? What do we need it for?
## Prerequisites
What do you need to create the provider? (Go, Terraform)
## Development 
How do we create a provider?
- Build the provider 
- Create the configuration (you can use the provided sample configs)
- Initialize terraform
- Provision
- Apply config 
## Usage
- Overview of how we can use the provider.
### Examples
Here we link to the config examples.

2019-09-20 14:24 UTC, bszwarc commented on README.md
>  - Website: https://www.terraform.io
To be honest, I don't think we need the information from lines 5-9. We have a link to terraform below, so I think that is enough.

2019-09-20 14:24 UTC, bszwarc commented on README.md
> +------------
```suggestion
```

2019-09-20 14:24 UTC, bszwarc commented on README.md
> +Requirements
```suggestion
Prerequisites
```

2019-09-20 14:24 UTC, bszwarc commented on README.md
> +Creating a new Terraform provider for Gardener using the Gardener client.This PoC contains a terraform provider that is meant to be executed by the terraform CLI.
```suggestion
```
Let's move this information to the Overview, and rework it a little bit.

2019-09-20 14:24 UTC, bszwarc commented on README.md
> +If you wish to work on the provider, you'll first need [Go](http://www.golang.org) installed on your machine (please check the [requirements](https://github.com/kyma-incubator/terraform-provider-gard
```suggestion
```
We don't need to repeat that the user needs Go, as it is already mentioned in the Requirements.

2019-09-20 14:24 UTC, bszwarc commented on README.md
> +Developing the Provider
```suggestion

```

2019-09-20 14:24 UTC, bszwarc commented on README.md
> +Using the provider
```suggestion
## Usage
```

2019-09-20 14:24 UTC, bszwarc commented on README.md
> +Building the provider
```suggestion
## Development
```
It may also be `Installation`, however, the question is if you install or create a provider.

2019-09-20 14:24 UTC, bszwarc commented on README.md
> +After building the provider as stated previously, you should create your terraform config file and run [`terraform init`](https://www.terraform.io/docs/commands/init.html) and Terraform will automati
```suggestion
```
I'm wondering if we should put these steps under `Development`. 
So you build your provider, add the config file, terraform installs the provider and you apply the config. We may point to the example configuration files that the user can use here. 
So my idea is to remove the text above - as it actually duplicates what is in the steps below (we can reuse some of the info in the steps) and have just the steps moved to the `Development` section.

2019-09-20 14:24 UTC, bszwarc commented on README.md
> +Examples of different configurations for different cluster providers could be found in the [examples](https://github.com/kyma-incubator/terraform-provider-gardener/tree/master/examples) folder.
```suggestion
1. Create your terraform configuration file.  You can use one of the sample configurations available in the [examples](https://github.com/kyma-incubator/terraform-provider-gardener/tree/master/examples) folder.
```

2019-09-20 14:24 UTC, bszwarc commented on README.md
> +1. Go to the provider example folder
```suggestion
```
I would remove this part and merge it with the one above.

2019-09-20 14:24 UTC, bszwarc commented on README.md
> +2. Edit the `main.tf` file providing the required gardener configuration:
Maybe we can add some details about what the file contains?

2019-09-20 14:24 UTC, bszwarc commented on README.md
>      > NOTE: To obtain the gardener secret and kubeconfig visit the gardener dashboard.
```suggestion
    > **NOTE:** To obtain the gardener secret and kubeconfig visit the gardener dashboard.
```
Maybe we can link to the Gardener dashboard or provide some instructions on how to obtain the secret and kubeconfig.

2019-09-20 14:24 UTC, bszwarc commented on examples/README.md
> +This directory contains a set of examples of using gardener services to deploy clusters of 3 different providers [aws](https://github.com/kyma-incubator/terraform-provider-gardener/tree/master/exampl
```suggestion
This folder contains a set of examples which use Gardener services to deploy [aws](https://github.com/kyma-incubator/terraform-provider-gardener/tree/master/examples/aws), [gcp](https://github.com/kyma-incubator/terraform-provider-gardener/tree/master/examples/gcp) and [azure](https://github.com/kyma-incubator/terraform-provider-gardener/tree/master/examples/azure) clusters. Although the configurations for these providers differ, they have the following common section:
```

2019-09-20 14:24 UTC, bszwarc commented on examples/README.md
> +The profile is the profile you want to deploy to in gardener. The <provider>_secret_binding is the provider secret binding defined for the profile that you want to use (there could be more than one s
```suggestion
This section includes the following parameters:
* **profile** - the profile you want to deploy to in gardener. 
* **<provider>_secret_binding** - the provider secret binding defined for the profile that you want to use. There might be more than one secret per provider for a profile.
* **kube_path** - the path for the kubeconfig file of the service bot of the profile. 
```

2019-09-20 14:24 UTC, bszwarc commented on examples/README.md
> +
```suggestion
## Overview
```

2019-09-20 14:24 UTC, bszwarc commented on examples/README.md
> +To run any example, clone the repository and run `terraform apply` within the example's own directory.
```suggestion
## Installation
Follow these steps to run an example:
1. Clone the `terraform-provider-gardener` repository.
2. Go to `terraform-provider-gardener/examples/{example_name}`.
3. Run  `terraform apply`. 
```

2019-09-20 14:24 UTC, bszwarc commented on examples/aws/README.md
> +# Gardener Aws Example
```suggestion
# Gardener AWS
```

2019-09-20 14:24 UTC, bszwarc commented on examples/aws/README.md
> +
```suggestion
## Overview
```

2019-09-20 14:24 UTC, bszwarc commented on examples/aws/README.md
> +This is a configuration example to deploy an aws cluster using gardener. You need to make sure that the secret binding parameter is "aws_secret_binding" for the deployment to work properly and that t
```suggestion
 Use this configuration example to deploy an AWS cluster using Gardener.
 >**NOTE**: For the example to work properly, make sure that the **secret_binding** parameter is set to `aws_secret_binding` and that the **resource** is `gardener_aws_shoot`.
```

2019-09-20 14:24 UTC, bszwarc commented on examples/aws/README.md
> +For now the following cidrs are obtrained from the similar clusters deployed on gardener, in the future these values should be obtained programatically.
```suggestion
Currently, values for the following CIDRs are obtained from the similar clusters deployed on Gardener:
```

2019-09-20 14:24 UTC, bszwarc commented on examples/aws/README.md
> +multiple workers can be defined as follows
```suggestion
You can also define multiple workers:
```

2019-09-20 14:24 UTC, bszwarc commented on examples/azure/README.md
> +For now the following cidrs are obtrained from the similar clusters deployed on gardener, in the future these values should be obtained programatically.
```suggestion
Currently, values for the following CIDRs are obtained from the similar clusters deployed on Gardener:
```

2019-09-20 14:24 UTC, bszwarc commented on examples/gcp/README.md
> +For now the following cidrs are obtrained from the similar clusters deployed on gardener, in the future these values should be obtained programatically.
```suggestion
Currently, values for the following CIDRs are obtained from the similar clusters deployed on Gardener:
```

2019-09-20 14:24 UTC, bszwarc commented on examples/azure/README.md
> +multiple workers can be defined as follows
```suggestion
You can also define multiple workers:
```

2019-09-20 14:24 UTC, bszwarc commented on examples/gcp/README.md
> +multiple workers can be defined as follows
```suggestion
You can also define multiple workers:
```

2019-09-20 14:24 UTC, bszwarc commented on examples/gcp/README.md
> +This is a configuration example to deploy an gcp cluster using gardener. You need to make sure that the secret binding parameter is "gcp_secret_binding" for the deployment to work properly and that t
```suggestion
Use this configuration example to deploy a GCP cluster using Gardener.
 >**NOTE**: For the example to work properly, make sure that the **secret_binding** parameter is set to `gcp_secret_binding` and that the **resource** is `gardener_gcp_shoot`.
```

2019-09-20 14:24 UTC, bszwarc commented on examples/azure/README.md
> +This is a configuration example to deploy an azure cluster using gardener. You need to make sure that the secret binding parameter is "azure_secret_binding" for the deployment to work properly and th
```suggestion
Use this configuration example to deploy an Azure cluster using Gardener.
 >**NOTE**: For the example to work properly, make sure that the **secret_binding** parameter is set to `azure_secret_binding` and that the **resource** is `gardener_azure_shoot`.
```

2019-09-20 14:24 UTC, bszwarc commented on examples/azure/README.md
> +# Gardener Azure Example
```suggestion
# Gardener Azure
```

2019-09-20 14:24 UTC, bszwarc commented on examples/gcp/README.md
> +# Gardener GCP Example
```suggestion
# Gardener GCP
```

2019-09-23 08:29 UTC, obadrawi commented on README.md
>  - Website: https://www.terraform.io
It's just that the other providers have it this way so I think we need to follow the same format

2019-09-23 08:37 UTC, obadrawi commented on README.md
>  - Website: https://www.terraform.io
It just that every other provider has the same template..so I wanted to follow the same format

2019-09-23 09:05 UTC, obadrawi commented on README.md
> +------------
We will leave format for now

2019-09-23 09:06 UTC, obadrawi commented on README.md
> +Requirements
We will leave it to follow other provider formats for now

2019-09-23 09:07 UTC, obadrawi commented on README.md
> +If you wish to work on the provider, you'll first need [Go](http://www.golang.org) installed on your machine (please check the [requirements](https://github.com/kyma-incubator/terraform-provider-gard
removed the developing provider part

2019-09-23 09:08 UTC, obadrawi commented on README.md
> +Developing the Provider
applied change

2019-09-23 09:33 UTC, obadrawi commented on README.md
> +After building the provider as stated previously, you should create your terraform config file and run [`terraform init`](https://www.terraform.io/docs/commands/init.html) and Terraform will automati
But this is actually the usage of the provider and it's different from the development. So I don't need to know anything of the inner working of the provider I just need to look at the examples

2019-09-23 09:39 UTC, obadrawi commented on README.md
>      > NOTE: To obtain the gardener secret and kubeconfig visit the gardener dashboard.
I have added the gardener dashboard link

2019-09-23 09:40 UTC, obadrawi commented on README.md
> +2. Edit the `main.tf` file providing the required gardener configuration:
added an example

2019-09-23 09:42 UTC, obadrawi commented on README.md
> +Building the provider
changed it to development

2019-09-23 09:42 UTC, obadrawi commented on README.md
> +Using the provider
applied change

2019-09-23 09:43 UTC, obadrawi commented on examples/README.md
> +This directory contains a set of examples of using gardener services to deploy clusters of 3 different providers [aws](https://github.com/kyma-incubator/terraform-provider-gardener/tree/master/exampl
applied change

2019-09-23 09:53 UTC, obadrawi commented on examples/README.md
> +
applied change

2019-09-23 09:55 UTC, obadrawi commented on examples/README.md
> +To run any example, clone the repository and run `terraform apply` within the example's own directory.
applied change

2019-09-23 09:55 UTC, obadrawi commented on examples/aws/README.md
> +# Gardener Aws Example
applied change

2019-09-23 09:56 UTC, obadrawi commented on examples/aws/README.md
> +
applied change

2019-09-23 09:56 UTC, obadrawi commented on examples/aws/README.md
> +This is a configuration example to deploy an aws cluster using gardener. You need to make sure that the secret binding parameter is "aws_secret_binding" for the deployment to work properly and that t
applied change

2019-09-23 09:57 UTC, obadrawi commented on examples/aws/README.md
> +For now the following cidrs are obtrained from the similar clusters deployed on gardener, in the future these values should be obtained programatically.
applied change

2019-09-23 09:57 UTC, obadrawi commented on examples/aws/README.md
> +multiple workers can be defined as follows
applied change

2019-09-23 09:57 UTC, obadrawi commented on examples/azure/README.md
> +For now the following cidrs are obtrained from the similar clusters deployed on gardener, in the future these values should be obtained programatically.
applied change

2019-09-23 09:57 UTC, obadrawi commented on examples/gcp/README.md
> +multiple workers can be defined as follows
applied change

2019-09-23 09:58 UTC, obadrawi commented on examples/gcp/README.md
> +This is a configuration example to deploy an gcp cluster using gardener. You need to make sure that the secret binding parameter is "gcp_secret_binding" for the deployment to work properly and that t
applied change

2019-09-23 09:58 UTC, obadrawi commented on examples/azure/README.md
> +This is a configuration example to deploy an azure cluster using gardener. You need to make sure that the secret binding parameter is "azure_secret_binding" for the deployment to work properly and th
applied change

2019-09-23 09:58 UTC, obadrawi commented on examples/azure/README.md
> +# Gardener Azure Example
applied change

2019-09-23 09:58 UTC, obadrawi commented on examples/gcp/README.md
> +# Gardener GCP Example
applied change

2019-09-30 08:53 UTC, bszwarc requested changes
Added some more comments :)

2019-09-30 08:53 UTC, bszwarc commented on README.md
> +After building the provider as stated previously, you should create your terraform config file and run [`terraform init`](https://www.terraform.io/docs/commands/init.html) and Terraform will automati
ok 👍

2019-09-30 08:53 UTC, bszwarc commented on README.md
> +### Requirements
```suggestion
## Prerequisites
```

2019-09-30 08:53 UTC, bszwarc commented on README.md
>  1. Resolve dependencies:
```suggestion
Perform the following steps to build the providers:

1. Resolve dependencies:
```

2019-09-30 08:53 UTC, bszwarc commented on README.md
>      >\* See https://www.terraform.io/docs/plugins/basics.html#installing-plugins for more information.
```suggestion
    >**NOTE**: For details on Terraform plugins [this](https://www.terraform.io/docs/plugins/basics.html#installing-plugins) document.
```

2019-09-30 08:53 UTC, bszwarc commented on README.md
> +1. Go to the provider [example](https://github.com/kyma-incubator/terraform-provider-gardener/tree/master/examples) folder
```suggestion
1. Go to the provider [example](https://github.com/kyma-incubator/terraform-provider-gardener/tree/master/examples) folder:
```

2019-09-30 08:53 UTC, bszwarc commented on README.md
> +2. Edit the `main.tf` file providing the required gardener configuration:
```suggestion
2. Edit the `main.tf` file and provide the required Gardener configuration:
```

2019-09-30 08:53 UTC, bszwarc commented on README.md
>      - Gardener project name
```suggestion
    - Project name
```

2019-09-30 08:53 UTC, bszwarc commented on README.md
>      - Gardener secret for the choosen cloud provider(s).
```suggestion
    - Gardener secret for the chosen cloud provider(s)
```

2019-09-30 08:53 UTC, bszwarc commented on README.md
>      - Path to the gardener kubeconfig.
```suggestion
    - Path to the Gardener kubeconfig
```

2019-09-30 08:53 UTC, bszwarc commented on README.md
> +    > **NOTE:** To obtain the gardener secret and kubeconfig visit the [gardener dashboard](https://dashboard.garden.canary.k8s.ondemand.com/login).
```suggestion
    > **NOTE:** To obtain the gardener secret and kubeconfig go to the [Gardener dashboard](https://dashboard.garden.canary.k8s.ondemand.com/login).
```

2019-09-30 08:53 UTC, bszwarc commented on README.md
> +3. Initialise terraform:
```suggestion
3. Initialize Terraform:
```

2019-09-30 08:53 UTC, bszwarc commented on README.md
> +Example config files can be found in the [examples](https://github.com/kyma-incubator/terraform-provider-gardener/tree/master/examples) folder for the three providers that we currently support.
```suggestion
See the [examples](https://github.com/kyma-incubator/terraform-provider-gardener/tree/master/examples) folder to view the configuration for the currently supported providers.
```

2019-09-30 08:53 UTC, bszwarc commented on README.md
> +After building the provider as stated previously, you should create your terraform config file and run [`terraform init`](https://www.terraform.io/docs/commands/init.html) and Terraform will automati
```suggestion
Perform the following steps to use the provider:
```

2019-09-30 09:14 UTC, obadrawi commented on README.md
> +### Requirements
applied changes

2019-09-30 09:15 UTC, obadrawi commented on README.md
>      >\* See https://www.terraform.io/docs/plugins/basics.html#installing-plugins for more information.
applied changes

2019-09-30 09:15 UTC, obadrawi commented on README.md
> +1. Go to the provider [example](https://github.com/kyma-incubator/terraform-provider-gardener/tree/master/examples) folder
applied changes

2019-09-30 09:15 UTC, obadrawi commented on README.md
>      - Path to the gardener kubeconfig.
applied changes

2019-09-30 09:15 UTC, obadrawi commented on README.md
> +    > **NOTE:** To obtain the gardener secret and kubeconfig visit the [gardener dashboard](https://dashboard.garden.canary.k8s.ondemand.com/login).
applied changes

2019-09-30 09:15 UTC, obadrawi commented on README.md
> +3. Initialise terraform:
applied changes

2019-09-30 09:15 UTC, obadrawi commented on README.md
> +Example config files can be found in the [examples](https://github.com/kyma-incubator/terraform-provider-gardener/tree/master/examples) folder for the three providers that we currently support.
applied changes

2019-09-30 09:15 UTC, obadrawi commented on README.md
> +After building the provider as stated previously, you should create your terraform config file and run [`terraform init`](https://www.terraform.io/docs/commands/init.html) and Terraform will automati
applied changes

2019-09-30 11:01 UTC, bszwarc requested changes

2019-09-30 11:01 UTC, bszwarc commented on README.md
> +    - Path to the Gardener kubeconfig.
```suggestion
    - Path to the Gardener kubeconfig
    
```

2019-09-30 11:01 UTC, bszwarc commented on README.md
> +    >**NOTE**: For details on Terraform plugins [this](https://www.terraform.io/docs/plugins/basics.html#installing-plugins) document.
```suggestion
    >**NOTE**: For details on Terraform plugins see [this](https://www.terraform.io/docs/plugins/basics.html#installing-plugins) document.
```

2019-09-30 11:01 UTC, bszwarc commented on README.md
>  3. Move the gardener provider binary into the terraform plugins folder*.
```suggestion
3. Move the Gardener provider binary to the Terraform plugins folder.

```

2019-09-30 12:56 UTC, bszwarc approved these changes

2019-09-30 12:58 UTC, clebs approved these changes

2019-09-30 12:59 UTC, merged